### ISSUE TITLE
Climbjump has a 1.44 speed boost in EveryJumpIsUltra variant

### ISSUE THREAD

**Issue by LozenChen** [maddie480/ExtendedVariantMode#25]
As described in title, EveryJumpIsUltra variant hooks Player.Jump(..) and Player.ClimbJump(), adds a 1.2 speed boost to the end of these functions
however, ClimbJump() calls Jump(..) internally, so a ClimbJump will actually give a 1.44 speed boost, instead of 1.2

not sure whether this should be patched or not

**Comment by maddie480** [comment]
Yeahhh I'm not sure of the impact fixing this would have on existing maps
😅 (I think there are maps that force ultras?)

**Comment by maddie480** [comment]
Someone pointed out that it was fixed in the past, but reverted as it broke a number of maps and TASes. So this bug is here to stay, I guess 😅 

- 0.25.8: "Climb jumps don't trigger double ultras anymore when using the *Every Jump is an Ultra* variant"
- 0.26.9: "Reverted a fix on *Every Jump is an Ultra* introduced in 0.25.8, as it broke a few maps and TASes"
